default:
  image: python:3.10.12

stages:
  - build
  - test

install-dependencies:
  tags:
    - main
    - dev
  stage: build
  script:
    - echo "Build virtual env"
    - python -m virtualenv venv
    - source venv/bin/activate
    - echo "Check python version, than install packages"
    - python -V
    - pip install -r requirements.txt
    - sleep 15

lint:
  tags:
   - main
   - dev
  stage: test
  script:
    - echo "Build virtual env"
    - python -m virtualenv venv
    - source venv/bin/activate
    - echo "Linting with ruff"
    - python -V
    - pip install -r requirements.txt
    - python -m ruff check .
    - sleep 10